TypeError: must be real number, not tuple

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Su\GenSim-main\gensim\sim_runner.py", line 200, in simulate_task
    total_reward = self.run_one_episode(dataset, expert, env, task, episode, seed)
  File "C:\Users\Su\GenSim-main\gensim\sim_runner.py", line 154, in run_one_episode
    act = expert.act(obs, info)
  File "C:\Users\Su\GenSim-main\cliport\tasks\task.py", line 206, in act
    place_pose = utils.multiply(targ_pose, pick_to_obj)
  File "C:\Users\Su\GenSim-main\cliport\utils\utils.py", line 243, in multiply
    return p.multiplyTransforms(pose0[0], pose0[1], pose1[0], pose1[1])
SystemError: <built-in function multiplyTransforms> returned a result with an error set
